// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/yw4c/trans-pb/p013keep/v1/keep.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	v1 "github.com/yw4c/trans-pb/p010user/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_92a3efb69c5961f6, []int{0}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Pagination struct {
	CurrentPage          int32    `protobuf:"varint,1,opt,name=CurrentPage,proto3" json:"CurrentPage,omitempty"`
	LastPage             int32    `protobuf:"varint,2,opt,name=LastPage,proto3" json:"LastPage,omitempty"`
	PerPage              int32    `protobuf:"varint,3,opt,name=PerPage,proto3" json:"PerPage,omitempty"`
	Total                int32    `protobuf:"varint,4,opt,name=Total,proto3" json:"Total,omitempty"`
	From                 int32    `protobuf:"varint,5,opt,name=From,proto3" json:"From,omitempty"`
	To                   int32    `protobuf:"varint,6,opt,name=To,proto3" json:"To,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pagination) Reset()         { *m = Pagination{} }
func (m *Pagination) String() string { return proto.CompactTextString(m) }
func (*Pagination) ProtoMessage()    {}
func (*Pagination) Descriptor() ([]byte, []int) {
	return fileDescriptor_92a3efb69c5961f6, []int{1}
}

func (m *Pagination) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pagination.Unmarshal(m, b)
}
func (m *Pagination) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pagination.Marshal(b, m, deterministic)
}
func (m *Pagination) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pagination.Merge(m, src)
}
func (m *Pagination) XXX_Size() int {
	return xxx_messageInfo_Pagination.Size(m)
}
func (m *Pagination) XXX_DiscardUnknown() {
	xxx_messageInfo_Pagination.DiscardUnknown(m)
}

var xxx_messageInfo_Pagination proto.InternalMessageInfo

func (m *Pagination) GetCurrentPage() int32 {
	if m != nil {
		return m.CurrentPage
	}
	return 0
}

func (m *Pagination) GetLastPage() int32 {
	if m != nil {
		return m.LastPage
	}
	return 0
}

func (m *Pagination) GetPerPage() int32 {
	if m != nil {
		return m.PerPage
	}
	return 0
}

func (m *Pagination) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *Pagination) GetFrom() int32 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *Pagination) GetTo() int32 {
	if m != nil {
		return m.To
	}
	return 0
}

type Keep struct {
	Id                   int32    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	En                   string   `protobuf:"bytes,2,opt,name=En,proto3" json:"En,omitempty"`
	Native               string   `protobuf:"bytes,3,opt,name=Native,proto3" json:"Native,omitempty"`
	EnScore              int32    `protobuf:"varint,4,opt,name=EnScore,proto3" json:"EnScore,omitempty"`
	NativeScore          int32    `protobuf:"varint,5,opt,name=NativeScore,proto3" json:"NativeScore,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Keep) Reset()         { *m = Keep{} }
func (m *Keep) String() string { return proto.CompactTextString(m) }
func (*Keep) ProtoMessage()    {}
func (*Keep) Descriptor() ([]byte, []int) {
	return fileDescriptor_92a3efb69c5961f6, []int{2}
}

func (m *Keep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Keep.Unmarshal(m, b)
}
func (m *Keep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Keep.Marshal(b, m, deterministic)
}
func (m *Keep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Keep.Merge(m, src)
}
func (m *Keep) XXX_Size() int {
	return xxx_messageInfo_Keep.Size(m)
}
func (m *Keep) XXX_DiscardUnknown() {
	xxx_messageInfo_Keep.DiscardUnknown(m)
}

var xxx_messageInfo_Keep proto.InternalMessageInfo

func (m *Keep) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Keep) GetEn() string {
	if m != nil {
		return m.En
	}
	return ""
}

func (m *Keep) GetNative() string {
	if m != nil {
		return m.Native
	}
	return ""
}

func (m *Keep) GetEnScore() int32 {
	if m != nil {
		return m.EnScore
	}
	return 0
}

func (m *Keep) GetNativeScore() int32 {
	if m != nil {
		return m.NativeScore
	}
	return 0
}

type StoreRequest struct {
	En                   string       `protobuf:"bytes,1,opt,name=En,proto3" json:"En,omitempty"`
	Native               string       `protobuf:"bytes,2,opt,name=Native,proto3" json:"Native,omitempty"`
	UserData             *v1.UserData `protobuf:"bytes,3,opt,name=UserData,proto3" json:"UserData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *StoreRequest) Reset()         { *m = StoreRequest{} }
func (m *StoreRequest) String() string { return proto.CompactTextString(m) }
func (*StoreRequest) ProtoMessage()    {}
func (*StoreRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_92a3efb69c5961f6, []int{3}
}

func (m *StoreRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreRequest.Unmarshal(m, b)
}
func (m *StoreRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreRequest.Marshal(b, m, deterministic)
}
func (m *StoreRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreRequest.Merge(m, src)
}
func (m *StoreRequest) XXX_Size() int {
	return xxx_messageInfo_StoreRequest.Size(m)
}
func (m *StoreRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StoreRequest proto.InternalMessageInfo

func (m *StoreRequest) GetEn() string {
	if m != nil {
		return m.En
	}
	return ""
}

func (m *StoreRequest) GetNative() string {
	if m != nil {
		return m.Native
	}
	return ""
}

func (m *StoreRequest) GetUserData() *v1.UserData {
	if m != nil {
		return m.UserData
	}
	return nil
}

type StoreReply struct {
	KeepId               int32    `protobuf:"varint,1,opt,name=KeepId,proto3" json:"KeepId,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StoreReply) Reset()         { *m = StoreReply{} }
func (m *StoreReply) String() string { return proto.CompactTextString(m) }
func (*StoreReply) ProtoMessage()    {}
func (*StoreReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_92a3efb69c5961f6, []int{4}
}

func (m *StoreReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreReply.Unmarshal(m, b)
}
func (m *StoreReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreReply.Marshal(b, m, deterministic)
}
func (m *StoreReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreReply.Merge(m, src)
}
func (m *StoreReply) XXX_Size() int {
	return xxx_messageInfo_StoreReply.Size(m)
}
func (m *StoreReply) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreReply.DiscardUnknown(m)
}

var xxx_messageInfo_StoreReply proto.InternalMessageInfo

func (m *StoreReply) GetKeepId() int32 {
	if m != nil {
		return m.KeepId
	}
	return 0
}

func (m *StoreReply) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type ListRequest struct {
	Page                 int32        `protobuf:"varint,1,opt,name=Page,proto3" json:"Page,omitempty"`
	PerPage              int32        `protobuf:"varint,2,opt,name=PerPage,proto3" json:"PerPage,omitempty"`
	RandomGroup          int32        `protobuf:"varint,3,opt,name=RandomGroup,proto3" json:"RandomGroup,omitempty"`
	Scores               []int32      `protobuf:"varint,4,rep,packed,name=Scores,proto3" json:"Scores,omitempty"`
	IsScoreNative        bool         `protobuf:"varint,5,opt,name=IsScoreNative,proto3" json:"IsScoreNative,omitempty"`
	UserData             *v1.UserData `protobuf:"bytes,6,opt,name=UserData,proto3" json:"UserData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_92a3efb69c5961f6, []int{5}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func (m *ListRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListRequest) GetPerPage() int32 {
	if m != nil {
		return m.PerPage
	}
	return 0
}

func (m *ListRequest) GetRandomGroup() int32 {
	if m != nil {
		return m.RandomGroup
	}
	return 0
}

func (m *ListRequest) GetScores() []int32 {
	if m != nil {
		return m.Scores
	}
	return nil
}

func (m *ListRequest) GetIsScoreNative() bool {
	if m != nil {
		return m.IsScoreNative
	}
	return false
}

func (m *ListRequest) GetUserData() *v1.UserData {
	if m != nil {
		return m.UserData
	}
	return nil
}

type ListReply struct {
	Pagination           *Pagination `protobuf:"bytes,1,opt,name=Pagination,proto3" json:"Pagination,omitempty"`
	List                 []*Keep     `protobuf:"bytes,2,rep,name=List,proto3" json:"List,omitempty"`
	Error                *Error      `protobuf:"bytes,3,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListReply) Reset()         { *m = ListReply{} }
func (m *ListReply) String() string { return proto.CompactTextString(m) }
func (*ListReply) ProtoMessage()    {}
func (*ListReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_92a3efb69c5961f6, []int{6}
}

func (m *ListReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListReply.Unmarshal(m, b)
}
func (m *ListReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListReply.Marshal(b, m, deterministic)
}
func (m *ListReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListReply.Merge(m, src)
}
func (m *ListReply) XXX_Size() int {
	return xxx_messageInfo_ListReply.Size(m)
}
func (m *ListReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ListReply.DiscardUnknown(m)
}

var xxx_messageInfo_ListReply proto.InternalMessageInfo

func (m *ListReply) GetPagination() *Pagination {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func (m *ListReply) GetList() []*Keep {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *ListReply) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type DeleteRequest struct {
	KeepId               int32    `protobuf:"varint,1,opt,name=KeepId,proto3" json:"KeepId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_92a3efb69c5961f6, []int{7}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetKeepId() int32 {
	if m != nil {
		return m.KeepId
	}
	return 0
}

type DeleteReply struct {
	KeepId               int32    `protobuf:"varint,1,opt,name=KeepId,proto3" json:"KeepId,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteReply) Reset()         { *m = DeleteReply{} }
func (m *DeleteReply) String() string { return proto.CompactTextString(m) }
func (*DeleteReply) ProtoMessage()    {}
func (*DeleteReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_92a3efb69c5961f6, []int{8}
}

func (m *DeleteReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteReply.Unmarshal(m, b)
}
func (m *DeleteReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteReply.Marshal(b, m, deterministic)
}
func (m *DeleteReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteReply.Merge(m, src)
}
func (m *DeleteReply) XXX_Size() int {
	return xxx_messageInfo_DeleteReply.Size(m)
}
func (m *DeleteReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteReply.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteReply proto.InternalMessageInfo

func (m *DeleteReply) GetKeepId() int32 {
	if m != nil {
		return m.KeepId
	}
	return 0
}

func (m *DeleteReply) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type ScoreRequest struct {
	KeepId               int32    `protobuf:"varint,1,opt,name=KeepId,proto3" json:"KeepId,omitempty"`
	Score                int32    `protobuf:"varint,2,opt,name=Score,proto3" json:"Score,omitempty"`
	IsScoreNative        bool     `protobuf:"varint,3,opt,name=IsScoreNative,proto3" json:"IsScoreNative,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScoreRequest) Reset()         { *m = ScoreRequest{} }
func (m *ScoreRequest) String() string { return proto.CompactTextString(m) }
func (*ScoreRequest) ProtoMessage()    {}
func (*ScoreRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_92a3efb69c5961f6, []int{9}
}

func (m *ScoreRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScoreRequest.Unmarshal(m, b)
}
func (m *ScoreRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScoreRequest.Marshal(b, m, deterministic)
}
func (m *ScoreRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScoreRequest.Merge(m, src)
}
func (m *ScoreRequest) XXX_Size() int {
	return xxx_messageInfo_ScoreRequest.Size(m)
}
func (m *ScoreRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ScoreRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ScoreRequest proto.InternalMessageInfo

func (m *ScoreRequest) GetKeepId() int32 {
	if m != nil {
		return m.KeepId
	}
	return 0
}

func (m *ScoreRequest) GetScore() int32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *ScoreRequest) GetIsScoreNative() bool {
	if m != nil {
		return m.IsScoreNative
	}
	return false
}

type ScoreReply struct {
	KeepId               int32    `protobuf:"varint,1,opt,name=KeepId,proto3" json:"KeepId,omitempty"`
	Error                *Error   `protobuf:"bytes,5,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScoreReply) Reset()         { *m = ScoreReply{} }
func (m *ScoreReply) String() string { return proto.CompactTextString(m) }
func (*ScoreReply) ProtoMessage()    {}
func (*ScoreReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_92a3efb69c5961f6, []int{10}
}

func (m *ScoreReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScoreReply.Unmarshal(m, b)
}
func (m *ScoreReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScoreReply.Marshal(b, m, deterministic)
}
func (m *ScoreReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScoreReply.Merge(m, src)
}
func (m *ScoreReply) XXX_Size() int {
	return xxx_messageInfo_ScoreReply.Size(m)
}
func (m *ScoreReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ScoreReply.DiscardUnknown(m)
}

var xxx_messageInfo_ScoreReply proto.InternalMessageInfo

func (m *ScoreReply) GetKeepId() int32 {
	if m != nil {
		return m.KeepId
	}
	return 0
}

func (m *ScoreReply) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterType((*Error)(nil), "keep.Error")
	proto.RegisterType((*Pagination)(nil), "keep.Pagination")
	proto.RegisterType((*Keep)(nil), "keep.Keep")
	proto.RegisterType((*StoreRequest)(nil), "keep.StoreRequest")
	proto.RegisterType((*StoreReply)(nil), "keep.StoreReply")
	proto.RegisterType((*ListRequest)(nil), "keep.ListRequest")
	proto.RegisterType((*ListReply)(nil), "keep.ListReply")
	proto.RegisterType((*DeleteRequest)(nil), "keep.DeleteRequest")
	proto.RegisterType((*DeleteReply)(nil), "keep.DeleteReply")
	proto.RegisterType((*ScoreRequest)(nil), "keep.ScoreRequest")
	proto.RegisterType((*ScoreReply)(nil), "keep.ScoreReply")
}

func init() {
	proto.RegisterFile("github.com/yw4c/trans-pb/p013keep/v1/keep.proto", fileDescriptor_92a3efb69c5961f6)
}

var fileDescriptor_92a3efb69c5961f6 = []byte{
	// 607 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0xc5, 0x8e, 0x1d, 0xda, 0x31, 0x2d, 0xed, 0x52, 0x21, 0x2b, 0x07, 0x64, 0xac, 0x0a, 0x22,
	0x04, 0x71, 0xea, 0xc2, 0x0f, 0xd0, 0x86, 0x12, 0x51, 0x50, 0xe4, 0x84, 0x0b, 0x37, 0xc7, 0x59,
	0x05, 0x8b, 0xc4, 0x6b, 0xd6, 0x9b, 0xa0, 0x70, 0xe2, 0x4b, 0xf8, 0x1d, 0xce, 0xfc, 0x11, 0xda,
	0x9d, 0x75, 0x62, 0x43, 0x02, 0x95, 0x38, 0x65, 0xe7, 0xcd, 0xec, 0xce, 0x9b, 0xf7, 0x26, 0x86,
	0x60, 0x9a, 0x8a, 0x8f, 0x8b, 0x71, 0x27, 0x61, 0xf3, 0x60, 0xf5, 0xe5, 0x79, 0x12, 0x08, 0x1e,
	0x67, 0xc5, 0xb3, 0x7c, 0x1c, 0xe4, 0xdd, 0xb3, 0xf3, 0x4f, 0x94, 0xe6, 0xc1, 0xf2, 0x2c, 0x90,
	0xbf, 0x9d, 0x9c, 0x33, 0xc1, 0x88, 0x25, 0xcf, 0xad, 0xbf, 0x5e, 0xeb, 0x2e, 0x0a, 0xca, 0xe5,
	0x35, 0xf9, 0x8b, 0xd7, 0xfc, 0x17, 0x60, 0xf7, 0x38, 0x67, 0x9c, 0x10, 0xb0, 0x2e, 0xd8, 0x84,
	0xba, 0x86, 0x67, 0xb4, 0xed, 0x48, 0x9d, 0x89, 0x0b, 0xb7, 0xdf, 0xd2, 0xa2, 0x88, 0xa7, 0xd4,
	0x35, 0x3d, 0xa3, 0xbd, 0x1f, 0x95, 0xa1, 0xff, 0xdd, 0x00, 0x18, 0xc4, 0xd3, 0x34, 0x8b, 0x45,
	0xca, 0x32, 0xe2, 0x81, 0x73, 0xb1, 0xe0, 0x9c, 0x66, 0x62, 0x20, 0x8b, 0xf1, 0x8d, 0x2a, 0x44,
	0x5a, 0xb0, 0x77, 0x1d, 0x17, 0x98, 0x36, 0x55, 0x7a, 0x1d, 0xcb, 0x36, 0x03, 0xca, 0x55, 0xaa,
	0xa1, 0x52, 0x65, 0x48, 0x4e, 0xc0, 0x1e, 0x31, 0x11, 0xcf, 0x5c, 0x4b, 0xe1, 0x18, 0x48, 0xaa,
	0xaf, 0x38, 0x9b, 0xbb, 0x36, 0x52, 0x95, 0x67, 0x72, 0x08, 0xe6, 0x88, 0xb9, 0x4d, 0x85, 0x98,
	0x23, 0xe6, 0x7f, 0x05, 0xeb, 0x0d, 0xa5, 0xb9, 0xc4, 0xfb, 0x13, 0x4d, 0xc8, 0xec, 0x4f, 0x64,
	0xdc, 0xcb, 0xf4, 0x34, 0x66, 0x2f, 0x23, 0xf7, 0xa1, 0xf9, 0x2e, 0x16, 0xe9, 0x12, 0x5b, 0xef,
	0x47, 0x3a, 0x92, 0x9c, 0x7a, 0xd9, 0x30, 0x61, 0x9c, 0xea, 0xde, 0x65, 0x28, 0x67, 0xc5, 0x1a,
	0xcc, 0x22, 0x89, 0x2a, 0xe4, 0x8f, 0xe1, 0xce, 0x50, 0x30, 0x4e, 0x23, 0xfa, 0x79, 0x41, 0x0b,
	0xa1, 0x7b, 0x1a, 0x5b, 0x7a, 0x9a, 0xb5, 0x9e, 0x4f, 0x60, 0xef, 0x7d, 0x41, 0xf9, 0x65, 0x2c,
	0x62, 0xc5, 0xc6, 0x09, 0x0f, 0x3b, 0xca, 0xaa, 0x12, 0x8d, 0xd6, 0x79, 0xff, 0x0a, 0x40, 0xf7,
	0xc8, 0x67, 0x2b, 0xf9, 0xa2, 0x9c, 0x76, 0x3d, 0xa9, 0x8e, 0xc8, 0x43, 0xed, 0xae, 0x6a, 0xe4,
	0x84, 0x4e, 0x47, 0x2d, 0x8c, 0x82, 0x22, 0xcc, 0xf8, 0x3f, 0x0c, 0x70, 0xae, 0xd3, 0x42, 0x94,
	0x64, 0x09, 0x58, 0x15, 0x0f, 0xad, 0xdf, 0x0d, 0x32, 0xeb, 0x06, 0x79, 0xe0, 0x44, 0x71, 0x36,
	0x61, 0xf3, 0x2b, 0xce, 0x16, 0xb9, 0xb6, 0xaf, 0x0a, 0x49, 0x6a, 0x4a, 0x95, 0xc2, 0xb5, 0xbc,
	0x86, 0xa4, 0x86, 0x11, 0x39, 0x85, 0x83, 0x7e, 0xa1, 0xce, 0x5a, 0x0b, 0x29, 0xe4, 0x5e, 0x54,
	0x07, 0x6b, 0x92, 0x34, 0xff, 0x21, 0xc9, 0x37, 0x03, 0xf6, 0x71, 0x12, 0x29, 0x49, 0xb7, 0xba,
	0xa0, 0x6a, 0x1a, 0x27, 0x3c, 0xc2, 0xf9, 0x37, 0x78, 0x54, 0x5d, 0xe2, 0x07, 0x60, 0xc9, 0xeb,
	0xae, 0xe9, 0x35, 0xda, 0x4e, 0x08, 0x58, 0x2b, 0x85, 0x8c, 0x14, 0xbe, 0x11, 0xb3, 0xb1, 0x53,
	0xcc, 0xc7, 0x70, 0x70, 0x49, 0x67, 0x54, 0xac, 0xad, 0xdf, 0x61, 0x8c, 0xff, 0x1a, 0x9c, 0xb2,
	0xf0, 0x3f, 0xfd, 0x93, 0xcb, 0x96, 0x54, 0x96, 0x6d, 0xd7, 0x53, 0x27, 0x60, 0xe3, 0xc2, 0xa2,
	0x83, 0x18, 0xfc, 0xe9, 0x42, 0x63, 0x8b, 0x0b, 0x6a, 0xd9, 0x92, 0x9b, 0x2f, 0x9b, 0xbd, 0x8b,
	0x6c, 0xf8, 0xd3, 0x00, 0x47, 0x56, 0x0f, 0x29, 0x5f, 0xa6, 0x09, 0x25, 0x01, 0xd8, 0x6a, 0x8b,
	0x09, 0xc1, 0xe2, 0xea, 0xdf, 0xa6, 0x75, 0x54, 0xc3, 0xf2, 0xd9, 0xca, 0xbf, 0x45, 0x9e, 0xa2,
	0x47, 0xe4, 0x18, 0x73, 0x95, 0xc5, 0x6d, 0xdd, 0xad, 0x42, 0x58, 0x1d, 0x42, 0x13, 0x55, 0x26,
	0xf7, 0x30, 0x59, 0x33, 0xa7, 0x75, 0x5c, 0x07, 0xf1, 0x4e, 0xa0, 0x75, 0x5a, 0x53, 0x4a, 0xb6,
	0x50, 0x4a, 0x36, 0x94, 0x5e, 0x3e, 0xfa, 0x70, 0x7a, 0x93, 0x6f, 0xf5, 0xb8, 0xa9, 0x3e, 0xb8,
	0xe7, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0xa1, 0x6e, 0x30, 0x09, 0xda, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// KeepServiceClient is the client API for KeepService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type KeepServiceClient interface {
	Store(ctx context.Context, in *StoreRequest, opts ...grpc.CallOption) (*StoreReply, error)
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListReply, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteReply, error)
	Score(ctx context.Context, in *ScoreRequest, opts ...grpc.CallOption) (*ScoreReply, error)
}

type keepServiceClient struct {
	cc *grpc.ClientConn
}

func NewKeepServiceClient(cc *grpc.ClientConn) KeepServiceClient {
	return &keepServiceClient{cc}
}

func (c *keepServiceClient) Store(ctx context.Context, in *StoreRequest, opts ...grpc.CallOption) (*StoreReply, error) {
	out := new(StoreReply)
	err := c.cc.Invoke(ctx, "/keep.KeepService/Store", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keepServiceClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListReply, error) {
	out := new(ListReply)
	err := c.cc.Invoke(ctx, "/keep.KeepService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keepServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteReply, error) {
	out := new(DeleteReply)
	err := c.cc.Invoke(ctx, "/keep.KeepService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keepServiceClient) Score(ctx context.Context, in *ScoreRequest, opts ...grpc.CallOption) (*ScoreReply, error) {
	out := new(ScoreReply)
	err := c.cc.Invoke(ctx, "/keep.KeepService/Score", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KeepServiceServer is the server API for KeepService service.
type KeepServiceServer interface {
	Store(context.Context, *StoreRequest) (*StoreReply, error)
	List(context.Context, *ListRequest) (*ListReply, error)
	Delete(context.Context, *DeleteRequest) (*DeleteReply, error)
	Score(context.Context, *ScoreRequest) (*ScoreReply, error)
}

// UnimplementedKeepServiceServer can be embedded to have forward compatible implementations.
type UnimplementedKeepServiceServer struct {
}

func (*UnimplementedKeepServiceServer) Store(ctx context.Context, req *StoreRequest) (*StoreReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Store not implemented")
}
func (*UnimplementedKeepServiceServer) List(ctx context.Context, req *ListRequest) (*ListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedKeepServiceServer) Delete(ctx context.Context, req *DeleteRequest) (*DeleteReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedKeepServiceServer) Score(ctx context.Context, req *ScoreRequest) (*ScoreReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Score not implemented")
}

func RegisterKeepServiceServer(s *grpc.Server, srv KeepServiceServer) {
	s.RegisterService(&_KeepService_serviceDesc, srv)
}

func _KeepService_Store_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeepServiceServer).Store(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/keep.KeepService/Store",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeepServiceServer).Store(ctx, req.(*StoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeepService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeepServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/keep.KeepService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeepServiceServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeepService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeepServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/keep.KeepService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeepServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeepService_Score_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeepServiceServer).Score(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/keep.KeepService/Score",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeepServiceServer).Score(ctx, req.(*ScoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _KeepService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "keep.KeepService",
	HandlerType: (*KeepServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Store",
			Handler:    _KeepService_Store_Handler,
		},
		{
			MethodName: "List",
			Handler:    _KeepService_List_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _KeepService_Delete_Handler,
		},
		{
			MethodName: "Score",
			Handler:    _KeepService_Score_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/yw4c/trans-pb/p013keep/v1/keep.proto",
}
