// Code generated by protoc-gen-go. DO NOT EDIT.
// source: p012dict/v1/dict.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	v1 "go_pb/p010user/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_5685f40a568283d9, []int{0}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Term struct {
	LexicalCategory      string   `protobuf:"bytes,1,opt,name=LexicalCategory,proto3" json:"LexicalCategory,omitempty"`
	Trans                []string `protobuf:"bytes,2,rep,name=Trans,proto3" json:"Trans,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Term) Reset()         { *m = Term{} }
func (m *Term) String() string { return proto.CompactTextString(m) }
func (*Term) ProtoMessage()    {}
func (*Term) Descriptor() ([]byte, []int) {
	return fileDescriptor_5685f40a568283d9, []int{1}
}

func (m *Term) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Term.Unmarshal(m, b)
}
func (m *Term) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Term.Marshal(b, m, deterministic)
}
func (m *Term) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Term.Merge(m, src)
}
func (m *Term) XXX_Size() int {
	return xxx_messageInfo_Term.Size(m)
}
func (m *Term) XXX_DiscardUnknown() {
	xxx_messageInfo_Term.DiscardUnknown(m)
}

var xxx_messageInfo_Term proto.InternalMessageInfo

func (m *Term) GetLexicalCategory() string {
	if m != nil {
		return m.LexicalCategory
	}
	return ""
}

func (m *Term) GetTrans() []string {
	if m != nil {
		return m.Trans
	}
	return nil
}

type Example struct {
	En                   string   `protobuf:"bytes,1,opt,name=En,proto3" json:"En,omitempty"`
	Native               string   `protobuf:"bytes,2,opt,name=Native,proto3" json:"Native,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Example) Reset()         { *m = Example{} }
func (m *Example) String() string { return proto.CompactTextString(m) }
func (*Example) ProtoMessage()    {}
func (*Example) Descriptor() ([]byte, []int) {
	return fileDescriptor_5685f40a568283d9, []int{2}
}

func (m *Example) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Example.Unmarshal(m, b)
}
func (m *Example) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Example.Marshal(b, m, deterministic)
}
func (m *Example) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Example.Merge(m, src)
}
func (m *Example) XXX_Size() int {
	return xxx_messageInfo_Example.Size(m)
}
func (m *Example) XXX_DiscardUnknown() {
	xxx_messageInfo_Example.DiscardUnknown(m)
}

var xxx_messageInfo_Example proto.InternalMessageInfo

func (m *Example) GetEn() string {
	if m != nil {
		return m.En
	}
	return ""
}

func (m *Example) GetNative() string {
	if m != nil {
		return m.Native
	}
	return ""
}

type Translation struct {
	En                   string     `protobuf:"bytes,1,opt,name=en,proto3" json:"en,omitempty"`
	Native               string     `protobuf:"bytes,2,opt,name=native,proto3" json:"native,omitempty"`
	Translation          string     `protobuf:"bytes,3,opt,name=translation,proto3" json:"translation,omitempty"`
	Terms                []*Term    `protobuf:"bytes,4,rep,name=terms,proto3" json:"terms,omitempty"`
	Examples             []*Example `protobuf:"bytes,5,rep,name=examples,proto3" json:"examples,omitempty"`
	PhoneticSpelling     string     `protobuf:"bytes,6,opt,name=phoneticSpelling,proto3" json:"phoneticSpelling,omitempty"`
	AudioFile            string     `protobuf:"bytes,7,opt,name=audioFile,proto3" json:"audioFile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Translation) Reset()         { *m = Translation{} }
func (m *Translation) String() string { return proto.CompactTextString(m) }
func (*Translation) ProtoMessage()    {}
func (*Translation) Descriptor() ([]byte, []int) {
	return fileDescriptor_5685f40a568283d9, []int{3}
}

func (m *Translation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Translation.Unmarshal(m, b)
}
func (m *Translation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Translation.Marshal(b, m, deterministic)
}
func (m *Translation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Translation.Merge(m, src)
}
func (m *Translation) XXX_Size() int {
	return xxx_messageInfo_Translation.Size(m)
}
func (m *Translation) XXX_DiscardUnknown() {
	xxx_messageInfo_Translation.DiscardUnknown(m)
}

var xxx_messageInfo_Translation proto.InternalMessageInfo

func (m *Translation) GetEn() string {
	if m != nil {
		return m.En
	}
	return ""
}

func (m *Translation) GetNative() string {
	if m != nil {
		return m.Native
	}
	return ""
}

func (m *Translation) GetTranslation() string {
	if m != nil {
		return m.Translation
	}
	return ""
}

func (m *Translation) GetTerms() []*Term {
	if m != nil {
		return m.Terms
	}
	return nil
}

func (m *Translation) GetExamples() []*Example {
	if m != nil {
		return m.Examples
	}
	return nil
}

func (m *Translation) GetPhoneticSpelling() string {
	if m != nil {
		return m.PhoneticSpelling
	}
	return ""
}

func (m *Translation) GetAudioFile() string {
	if m != nil {
		return m.AudioFile
	}
	return ""
}

type TranslateRequest struct {
	Word                 string       `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	UserData             *v1.UserData `protobuf:"bytes,2,opt,name=UserData,proto3" json:"UserData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *TranslateRequest) Reset()         { *m = TranslateRequest{} }
func (m *TranslateRequest) String() string { return proto.CompactTextString(m) }
func (*TranslateRequest) ProtoMessage()    {}
func (*TranslateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5685f40a568283d9, []int{4}
}

func (m *TranslateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TranslateRequest.Unmarshal(m, b)
}
func (m *TranslateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TranslateRequest.Marshal(b, m, deterministic)
}
func (m *TranslateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TranslateRequest.Merge(m, src)
}
func (m *TranslateRequest) XXX_Size() int {
	return xxx_messageInfo_TranslateRequest.Size(m)
}
func (m *TranslateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TranslateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TranslateRequest proto.InternalMessageInfo

func (m *TranslateRequest) GetWord() string {
	if m != nil {
		return m.Word
	}
	return ""
}

func (m *TranslateRequest) GetUserData() *v1.UserData {
	if m != nil {
		return m.UserData
	}
	return nil
}

func init() {
	proto.RegisterType((*Error)(nil), "dict.Error")
	proto.RegisterType((*Term)(nil), "dict.Term")
	proto.RegisterType((*Example)(nil), "dict.Example")
	proto.RegisterType((*Translation)(nil), "dict.Translation")
	proto.RegisterType((*TranslateRequest)(nil), "dict.TranslateRequest")
}

func init() { proto.RegisterFile("p012dict/v1/dict.proto", fileDescriptor_5685f40a568283d9) }

var fileDescriptor_5685f40a568283d9 = []byte{
	// 391 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x52, 0x41, 0x6f, 0xd3, 0x30,
	0x14, 0xa6, 0x6d, 0xd2, 0x2e, 0xaf, 0x62, 0x6c, 0x0f, 0x54, 0x59, 0x13, 0x87, 0x28, 0xa7, 0xb0,
	0x43, 0xbb, 0x16, 0x21, 0x71, 0x44, 0x6c, 0xd9, 0x09, 0x38, 0x98, 0x71, 0xe1, 0x82, 0xbc, 0xe4,
	0x29, 0x58, 0x4a, 0xed, 0x60, 0xbb, 0x63, 0xfc, 0x69, 0x7e, 0x03, 0xb2, 0x93, 0x74, 0x5b, 0x39,
	0xf9, 0x7d, 0xdf, 0xf7, 0xbe, 0xbc, 0x7c, 0xf6, 0x83, 0x45, 0x7b, 0xb1, 0xde, 0x54, 0xb2, 0x74,
	0xab, 0xbb, 0xf5, 0xca, 0x9f, 0xcb, 0xd6, 0x68, 0xa7, 0x31, 0xf2, 0xf5, 0x99, 0x57, 0x2f, 0x76,
	0x96, 0x8c, 0x57, 0xfd, 0xd9, 0xa9, 0xd9, 0x3b, 0x88, 0x0b, 0x63, 0xb4, 0x41, 0x84, 0xe8, 0x52,
	0x57, 0xc4, 0x46, 0xe9, 0x28, 0x8f, 0x79, 0xa8, 0x91, 0xc1, 0xec, 0x33, 0x59, 0x2b, 0x6a, 0x62,
	0xe3, 0x74, 0x94, 0x27, 0x7c, 0x80, 0xd9, 0x35, 0x44, 0x37, 0x64, 0xb6, 0x98, 0xc3, 0x8b, 0x4f,
	0x74, 0x2f, 0x4b, 0xd1, 0x5c, 0x0a, 0x47, 0xb5, 0x36, 0x7f, 0xc2, 0x07, 0x12, 0x7e, 0x48, 0xe3,
	0x2b, 0x88, 0x6f, 0x8c, 0x50, 0x96, 0x8d, 0xd3, 0x49, 0x9e, 0xf0, 0x0e, 0x64, 0x6b, 0x98, 0x15,
	0xf7, 0x62, 0xdb, 0x36, 0x84, 0xc7, 0x30, 0x2e, 0x54, 0xef, 0x1e, 0x17, 0x0a, 0x17, 0x30, 0xfd,
	0x22, 0x9c, 0xbc, 0x1b, 0x66, 0xf7, 0x28, 0xfb, 0x3b, 0x82, 0x79, 0x30, 0x37, 0xc2, 0x49, 0xad,
	0xbc, 0x8f, 0xf6, 0x3e, 0x0a, 0x3e, 0xf5, 0xc4, 0xd7, 0x21, 0x4c, 0x61, 0xee, 0x1e, 0x6c, 0x6c,
	0x12, 0xc4, 0xc7, 0x14, 0xa6, 0x10, 0x3b, 0x32, 0x5b, 0xcb, 0xa2, 0x74, 0x92, 0xcf, 0x37, 0xb0,
	0x0c, 0xb7, 0xe8, 0x73, 0xf2, 0x4e, 0xc0, 0x37, 0x70, 0x44, 0xdd, 0xef, 0x5a, 0x16, 0x87, 0xa6,
	0xe7, 0x5d, 0x53, 0x1f, 0x82, 0xef, 0x65, 0x3c, 0x87, 0x93, 0xf6, 0xa7, 0x56, 0xe4, 0x64, 0xf9,
	0xb5, 0xa5, 0xa6, 0x91, 0xaa, 0x66, 0xd3, 0x30, 0xf3, 0x3f, 0x1e, 0x5f, 0x43, 0x22, 0x76, 0x95,
	0xd4, 0xd7, 0xb2, 0x21, 0x36, 0x0b, 0x4d, 0x0f, 0x44, 0xc6, 0xe1, 0x64, 0xc8, 0x4b, 0x9c, 0x7e,
	0xed, 0xc8, 0x3a, 0xff, 0x5a, 0xbf, 0xb5, 0xa9, 0xfa, 0xd8, 0xa1, 0xc6, 0x73, 0x38, 0xfa, 0x66,
	0xc9, 0x5c, 0x09, 0x27, 0x42, 0xf4, 0xf9, 0xe6, 0x78, 0x19, 0x5e, 0x7a, 0x60, 0xf9, 0x5e, 0xdf,
	0x7c, 0x80, 0xe8, 0x4a, 0x96, 0x0e, 0xdf, 0x43, 0x32, 0xdc, 0x00, 0xe1, 0xa2, 0x0f, 0x7c, 0x30,
	0xec, 0xec, 0xf4, 0x29, 0x2f, 0xb5, 0xca, 0x9e, 0x7d, 0x7c, 0xf9, 0xfd, 0xb4, 0xd6, 0x3f, 0xda,
	0xdb, 0xd5, 0xa3, 0xb5, 0xbb, 0x9d, 0x86, 0xa5, 0x7a, 0xfb, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xf7,
	0x31, 0xce, 0xbc, 0x8c, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DictClient is the client API for Dict service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DictClient interface {
	Translate(ctx context.Context, in *TranslateRequest, opts ...grpc.CallOption) (*Translation, error)
}

type dictClient struct {
	cc *grpc.ClientConn
}

func NewDictClient(cc *grpc.ClientConn) DictClient {
	return &dictClient{cc}
}

func (c *dictClient) Translate(ctx context.Context, in *TranslateRequest, opts ...grpc.CallOption) (*Translation, error) {
	out := new(Translation)
	err := c.cc.Invoke(ctx, "/dict.Dict/translate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DictServer is the server API for Dict service.
type DictServer interface {
	Translate(context.Context, *TranslateRequest) (*Translation, error)
}

// UnimplementedDictServer can be embedded to have forward compatible implementations.
type UnimplementedDictServer struct {
}

func (*UnimplementedDictServer) Translate(ctx context.Context, req *TranslateRequest) (*Translation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Translate not implemented")
}

func RegisterDictServer(s *grpc.Server, srv DictServer) {
	s.RegisterService(&_Dict_serviceDesc, srv)
}

func _Dict_Translate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TranslateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DictServer).Translate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dict.Dict/Translate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DictServer).Translate(ctx, req.(*TranslateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Dict_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dict.Dict",
	HandlerType: (*DictServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "translate",
			Handler:    _Dict_Translate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "p012dict/v1/dict.proto",
}
